# Generated by Django 5.2.10 on 2026-01-12 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakroomapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('G', 'Gaming'), ('F', 'Food'), ('P', 'Pool'), ('C', 'Combined')], default=datetime.datetime(2026, 1, 12, 6, 20, 15, 109549, tzinfo=datetime.timezone.utc), max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='gst',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='service_charge',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
