# Generated by Django 5.2.10 on 2026-01-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakroomapp', '0002_bill_bill_type_bill_gst_bill_service_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
